[2025-02-28T03:04:52.664+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-28T03:04:52.689+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_postgres_to_parquet.extract_task manual__2025-02-28T02:59:48.294625+00:00 [queued]>
[2025-02-28T03:04:52.705+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_postgres_to_parquet.extract_task manual__2025-02-28T02:59:48.294625+00:00 [queued]>
[2025-02-28T03:04:52.706+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-02-28T03:04:52.727+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_task> on 2025-02-28 02:59:48.294625+00:00
[2025-02-28T03:04:52.736+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_postgres_to_parquet', 'extract_task', 'manual__2025-02-28T02:59:48.294625+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/etl_process_to_parquet.py', '--cfg-path', '/tmp/tmp7wlak34d']
[2025-02-28T03:04:52.738+0000] {standard_task_runner.py:105} INFO - Job 79: Subtask extract_task
[2025-02-28T03:04:52.742+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3530) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-28T03:04:52.743+0000] {standard_task_runner.py:72} INFO - Started process 3585 to run task
[2025-02-28T03:04:52.803+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_postgres_to_parquet.extract_task manual__2025-02-28T02:59:48.294625+00:00 [running]> on host 151d4861bf1b
[2025-02-28T03:04:52.900+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_postgres_to_parquet' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-28T02:59:48.294625+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-28T02:59:48.294625+00:00'
[2025-02-28T03:04:52.902+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-28T03:04:52.903+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-28T03:04:52.904+0000] {logging_mixin.py:190} INFO - Current task name:extract_task state:running start_date:2025-02-28 03:04:52.690473+00:00
[2025-02-28T03:04:52.905+0000] {logging_mixin.py:190} INFO - Dag name:etl_postgres_to_parquet and current dag run status:running
[2025-02-28T03:04:52.905+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-28T03:04:52.907+0000] {logging_mixin.py:190} INFO - üîç Tentando se conectar ao PostgreSQL...
[2025-02-28T03:04:52.917+0000] {base.py:84} INFO - Retrieving connection '***_default'
[2025-02-28T03:04:52.994+0000] {logging_mixin.py:190} INFO - ‚úÖ Conex√£o com o PostgreSQL estabelecida com sucesso!
[2025-02-28T03:04:52.998+0000] {logging_mixin.py:190} INFO - ‚úÖ Teste de conex√£o bem-sucedido! PostgreSQL respondeu corretamente.
[2025-02-28T03:04:52.999+0000] {logging_mixin.py:190} INFO - üì¶ Executando query para extrair os dados...
[2025-02-28T03:04:53.013+0000] {logging_mixin.py:190} WARNING - /opt/***/dags/etl_process_to_parquet.py:36 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-02-28T03:04:53.026+0000] {logging_mixin.py:190} INFO - ‚úÖ 8 registros extra√≠dos da tabela `produtos`.
[2025-02-28T03:04:53.036+0000] {logging_mixin.py:190} INFO - ‚ùå Erro na extra√ß√£o dos dados: Cannot save file into a non-existent directory: '/opt/***/dags/output'
[2025-02-28T03:04:53.037+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_process_to_parquet.py", line 43, in extract_data
    df.to_csv(raw_csv_path, index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/opt/***/dags/output'
[2025-02-28T03:04:53.065+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-28T03:04:53.066+0000] {logging_mixin.py:190} INFO - Task start:2025-02-28 03:04:52.690473+00:00 end:2025-02-28 03:04:53.065039+00:00 duration:0.374566
[2025-02-28T03:04:53.067+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_task> dag:<DAG: etl_***_to_parquet> dagrun:<DagRun etl_***_to_parquet @ 2025-02-28 02:59:48.294625+00:00: manual__2025-02-28T02:59:48.294625+00:00, state:running, queued_at: 2025-02-28 02:59:48.331267+00:00. externally triggered: True>
[2025-02-28T03:04:53.067+0000] {logging_mixin.py:190} INFO - Failure caused by Cannot save file into a non-existent directory: '/opt/***/dags/output'
[2025-02-28T03:04:53.068+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=etl_***_to_parquet, task_id=extract_task, run_id=manual__2025-02-28T02:59:48.294625+00:00, execution_date=20250228T025948, start_date=20250228T030452, end_date=20250228T030453
[2025-02-28T03:04:53.107+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-28T03:04:53.108+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 79 for task extract_task (Cannot save file into a non-existent directory: '/opt/***/dags/output'; 3585)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_process_to_parquet.py", line 43, in extract_data
    df.to_csv(raw_csv_path, index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/opt/***/dags/output'
[2025-02-28T03:04:53.161+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-28T03:04:53.228+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-28T03:04:53.239+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
