[2025-02-28T17:59:37.629+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-28T17:59:37.647+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ha_etl_process.extract_task scheduled__2025-02-27T00:00:00+00:00 [queued]>
[2025-02-28T17:59:37.657+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ha_etl_process.extract_task scheduled__2025-02-27T00:00:00+00:00 [queued]>
[2025-02-28T17:59:37.657+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-02-28T17:59:37.680+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_task> on 2025-02-27 00:00:00+00:00
[2025-02-28T17:59:37.692+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ha_etl_process', 'extract_task', 'scheduled__2025-02-27T00:00:00+00:00', '--job-id', '126', '--raw', '--subdir', 'DAGS_FOLDER/ha_etl_process.py', '--cfg-path', '/tmp/tmpcx040e48']
[2025-02-28T17:59:37.694+0000] {standard_task_runner.py:105} INFO - Job 126: Subtask extract_task
[2025-02-28T17:59:37.698+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=189) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-28T17:59:37.699+0000] {standard_task_runner.py:72} INFO - Started process 268 to run task
[2025-02-28T17:59:37.751+0000] {task_command.py:467} INFO - Running <TaskInstance: ha_etl_process.extract_task scheduled__2025-02-27T00:00:00+00:00 [running]> on host 151d4861bf1b
[2025-02-28T17:59:37.886+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ha_etl_process' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-27T00:00:00+00:00'
[2025-02-28T17:59:37.887+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-28T17:59:37.888+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-28T17:59:37.888+0000] {logging_mixin.py:190} INFO - Current task name:extract_task state:running start_date:2025-02-28 17:59:37.648115+00:00
[2025-02-28T17:59:37.888+0000] {logging_mixin.py:190} INFO - Dag name:ha_etl_process and current dag run status:running
[2025-02-28T17:59:37.889+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-28T17:59:37.890+0000] {logging_mixin.py:190} INFO - üîç Tentando se conectar ao Home Assistant...
[2025-02-28T17:59:37.890+0000] {logging_mixin.py:190} INFO - üì¶ Extraindo hist√≥rico da entidade sensor.abc_consumo_ativo_total...
[2025-02-28T17:59:38.420+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è Nenhum dado retornado.
[2025-02-28T17:59:38.431+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è Nenhum dado retornado.
[2025-02-28T17:59:38.443+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è Nenhum dado retornado.
[2025-02-28T17:59:38.453+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è Nenhum dado retornado.
[2025-02-28T17:59:38.469+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è Nenhum dado retornado.
[2025-02-28T17:59:38.481+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è Nenhum dado retornado.
[2025-02-28T17:59:38.490+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è Nenhum dado retornado.
[2025-02-28T17:59:38.499+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è Nenhum dado retornado.
[2025-02-28T17:59:38.508+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è Nenhum dado retornado.
[2025-02-28T17:59:38.517+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è Nenhum dado retornado.
[2025-02-28T17:59:38.526+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è Nenhum dado retornado.
[2025-02-28T17:59:38.538+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è Nenhum dado retornado.
[2025-02-28T17:59:38.548+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è Nenhum dado retornado.
[2025-02-28T17:59:38.557+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è Nenhum dado retornado.
[2025-02-28T17:59:38.572+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è Nenhum dado retornado.
[2025-02-28T17:59:38.581+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è Nenhum dado retornado.
[2025-02-28T17:59:38.593+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è Nenhum dado retornado.
[2025-02-28T17:59:38.603+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è Nenhum dado retornado.
[2025-02-28T17:59:38.613+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è Nenhum dado retornado.
[2025-02-28T17:59:38.624+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è Nenhum dado retornado.
[2025-02-28T17:59:38.635+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è Nenhum dado retornado.
[2025-02-28T17:59:38.646+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è Nenhum dado retornado.
[2025-02-28T17:59:38.665+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è Nenhum dado retornado.
[2025-02-28T17:59:38.677+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è Nenhum dado retornado.
[2025-02-28T17:59:38.685+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è Nenhum dado retornado.
[2025-02-28T17:59:38.693+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è Nenhum dado retornado.
[2025-02-28T17:59:38.703+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è Nenhum dado retornado.
[2025-02-28T17:59:38.712+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è Nenhum dado retornado.
[2025-02-28T17:59:38.721+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è Nenhum dado retornado.
[2025-02-28T17:59:38.730+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è Nenhum dado retornado.
[2025-02-28T17:59:38.743+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è Nenhum dado retornado.
[2025-02-28T17:59:38.758+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è Nenhum dado retornado.
[2025-02-28T17:59:38.764+0000] {logging_mixin.py:190} INFO - ‚úÖ 1841 registros extra√≠dos.
[2025-02-28T17:59:38.787+0000] {logging_mixin.py:190} INFO - üìÅ Dados salvos em /tmp/raw_data.csv
[2025-02-28T17:59:38.788+0000] {logging_mixin.py:190} INFO - ‚ùå Erro na extra√ß√£o dos dados: DataFrame index must be unique for orient='columns'.
[2025-02-28T17:59:38.789+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ha_etl_process.py", line 119, in extract_data
    return history.to_json()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 2629, in to_json
    return json.to_json(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/json/_json.py", line 195, in to_json
    s = writer(
        ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/json/_json.py", line 251, in __init__
    self._format_axes()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/json/_json.py", line 307, in _format_axes
    raise ValueError(
ValueError: DataFrame index must be unique for orient='columns'.
[2025-02-28T17:59:38.803+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-28T17:59:38.804+0000] {logging_mixin.py:190} INFO - Task start:2025-02-28 17:59:37.648115+00:00 end:2025-02-28 17:59:38.803310+00:00 duration:1.155195
[2025-02-28T17:59:38.805+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_task> dag:<DAG: ha_etl_process> dagrun:<DagRun ha_etl_process @ 2025-02-27 00:00:00+00:00: scheduled__2025-02-27T00:00:00+00:00, state:running, queued_at: 2025-02-28 17:54:19.144082+00:00. externally triggered: False>
[2025-02-28T17:59:38.805+0000] {logging_mixin.py:190} INFO - Failure caused by DataFrame index must be unique for orient='columns'.
[2025-02-28T17:59:38.806+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=ha_etl_process, task_id=extract_task, run_id=scheduled__2025-02-27T00:00:00+00:00, execution_date=20250227T000000, start_date=20250228T175937, end_date=20250228T175938
[2025-02-28T17:59:38.842+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-28T17:59:38.843+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 126 for task extract_task (DataFrame index must be unique for orient='columns'.; 268)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ha_etl_process.py", line 119, in extract_data
    return history.to_json()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 2629, in to_json
    return json.to_json(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/json/_json.py", line 195, in to_json
    s = writer(
        ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/json/_json.py", line 251, in __init__
    self._format_axes()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/json/_json.py", line 307, in _format_axes
    raise ValueError(
ValueError: DataFrame index must be unique for orient='columns'.
[2025-02-28T17:59:38.877+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-28T17:59:38.907+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-28T17:59:38.915+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
